
package com.liferay.wsrp.soap.v2.intf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1
 * Fri Jun 13 17:58:34 PDT 2008
 * Generated source version: 2.1
 * 
 */

@WebFault(name = "AccessDenied", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")

public class AccessDenied extends Exception {
    public static final long serialVersionUID = 20080613175834L;
    
    private com.liferay.wsrp.soap.v2.types.AccessDeniedFault accessDenied;

    public AccessDenied() {
        super();
    }
    
    public AccessDenied(String message) {
        super(message);
    }
    
    public AccessDenied(String message, Throwable cause) {
        super(message, cause);
    }

    public AccessDenied(String message, com.liferay.wsrp.soap.v2.types.AccessDeniedFault accessDenied) {
        super(message);
        this.accessDenied = accessDenied;
    }

    public AccessDenied(String message, com.liferay.wsrp.soap.v2.types.AccessDeniedFault accessDenied, Throwable cause) {
        super(message, cause);
        this.accessDenied = accessDenied;
    }

    public com.liferay.wsrp.soap.v2.types.AccessDeniedFault getFaultInfo() {
        return this.accessDenied;
    }
}
