
package com.liferay.wsrp.soap.v2.intf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1
 * Fri Jun 13 17:58:34 PDT 2008
 * Generated source version: 2.1
 * 
 */

@WebFault(name = "InvalidCookie", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")

public class InvalidCookie extends Exception {
    public static final long serialVersionUID = 20080613175834L;
    
    private com.liferay.wsrp.soap.v2.types.InvalidCookieFault invalidCookie;

    public InvalidCookie() {
        super();
    }
    
    public InvalidCookie(String message) {
        super(message);
    }
    
    public InvalidCookie(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidCookie(String message, com.liferay.wsrp.soap.v2.types.InvalidCookieFault invalidCookie) {
        super(message);
        this.invalidCookie = invalidCookie;
    }

    public InvalidCookie(String message, com.liferay.wsrp.soap.v2.types.InvalidCookieFault invalidCookie, Throwable cause) {
        super(message, cause);
        this.invalidCookie = invalidCookie;
    }

    public com.liferay.wsrp.soap.v2.types.InvalidCookieFault getFaultInfo() {
        return this.invalidCookie;
    }
}
