/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.sharing.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.asset.sharing.service.persistence.AssetSharingEntryPK;

import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AssetSharingEntry service. Represents a row in the &quot;AssetSharing_AssetSharingEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.asset.sharing.model.impl.AssetSharingEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.asset.sharing.model.impl.AssetSharingEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetSharingEntry
 * @see com.liferay.asset.sharing.model.impl.AssetSharingEntryImpl
 * @see com.liferay.asset.sharing.model.impl.AssetSharingEntryModelImpl
 * @generated
 */
@ProviderType
public interface AssetSharingEntryModel extends AttachedModel,
	BaseModel<AssetSharingEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset sharing entry model instance should use the {@link AssetSharingEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this asset sharing entry.
	 *
	 * @return the primary key of this asset sharing entry
	 */
	public AssetSharingEntryPK getPrimaryKey();

	/**
	 * Sets the primary key of this asset sharing entry.
	 *
	 * @param primaryKey the primary key of this asset sharing entry
	 */
	public void setPrimaryKey(AssetSharingEntryPK primaryKey);

	/**
	 * Returns the fully qualified class name of this asset sharing entry.
	 *
	 * @return the fully qualified class name of this asset sharing entry
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this asset sharing entry.
	 *
	 * @return the class name ID of this asset sharing entry
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this asset sharing entry.
	 *
	 * @param classNameId the class name ID of this asset sharing entry
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this asset sharing entry.
	 *
	 * @return the class p k of this asset sharing entry
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this asset sharing entry.
	 *
	 * @param classPK the class p k of this asset sharing entry
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the shared to class name ID of this asset sharing entry.
	 *
	 * @return the shared to class name ID of this asset sharing entry
	 */
	public long getSharedToClassNameId();

	/**
	 * Sets the shared to class name ID of this asset sharing entry.
	 *
	 * @param sharedToClassNameId the shared to class name ID of this asset sharing entry
	 */
	public void setSharedToClassNameId(long sharedToClassNameId);

	/**
	 * Returns the shared to class p k of this asset sharing entry.
	 *
	 * @return the shared to class p k of this asset sharing entry
	 */
	public long getSharedToClassPK();

	/**
	 * Sets the shared to class p k of this asset sharing entry.
	 *
	 * @param sharedToClassPK the shared to class p k of this asset sharing entry
	 */
	public void setSharedToClassPK(long sharedToClassPK);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.asset.sharing.model.AssetSharingEntry assetSharingEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.asset.sharing.model.AssetSharingEntry> toCacheModel();

	@Override
	public com.liferay.asset.sharing.model.AssetSharingEntry toEscapedModel();

	@Override
	public com.liferay.asset.sharing.model.AssetSharingEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}