/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.saml.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.saml.model.SPSession;
import com.liferay.portal.saml.model.SPSessionModel;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the SPSession service. Represents a row in the &quot;SAML_SPSession&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.portal.saml.model.SPSessionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SPSessionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SPSessionImpl
 * @see com.liferay.portal.saml.model.SPSession
 * @see com.liferay.portal.saml.model.SPSessionModel
 * @generated
 */
public class SPSessionModelImpl extends BaseModelImpl<SPSession>
	implements SPSessionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a s p session model instance should use the {@link com.liferay.portal.saml.model.SPSession} interface instead.
	 */
	public static final String TABLE_NAME = "SAML_SPSession";
	public static final Object[][] TABLE_COLUMNS = {
			{ "spSessionId", new Integer(Types.BIGINT) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "userId", new Integer(Types.BIGINT) },
			{ "createDate", new Integer(Types.TIMESTAMP) },
			{ "ssoSessionId", new Integer(Types.BIGINT) },
			{ "issuer", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table SAML_SPSession (spSessionId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,ssoSessionId LONG,issuer VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SAML_SPSession";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.portal.saml.model.SPSession"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.portal.saml.model.SPSession"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.saml.model.SPSession"));

	public SPSessionModelImpl() {
	}

	public long getPrimaryKey() {
		return _spSessionId;
	}

	public void setPrimaryKey(long pk) {
		setSpSessionId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_spSessionId);
	}

	public long getSpSessionId() {
		return _spSessionId;
	}

	public void setSpSessionId(long spSessionId) {
		_spSessionId = spSessionId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public long getSsoSessionId() {
		return _ssoSessionId;
	}

	public void setSsoSessionId(long ssoSessionId) {
		_ssoSessionId = ssoSessionId;

		if (!_setOriginalSsoSessionId) {
			_setOriginalSsoSessionId = true;

			_originalSsoSessionId = ssoSessionId;
		}
	}

	public long getOriginalSsoSessionId() {
		return _originalSsoSessionId;
	}

	public String getIssuer() {
		if (_issuer == null) {
			return StringPool.BLANK;
		}
		else {
			return _issuer;
		}
	}

	public void setIssuer(String issuer) {
		_issuer = issuer;

		if (_originalIssuer == null) {
			_originalIssuer = issuer;
		}
	}

	public String getOriginalIssuer() {
		return GetterUtil.getString(_originalIssuer);
	}

	public SPSession toEscapedModel() {
		if (isEscapedModel()) {
			return (SPSession)this;
		}
		else {
			return (SPSession)Proxy.newProxyInstance(SPSession.class.getClassLoader(),
				new Class[] { SPSession.class }, new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
					SPSession.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		SPSessionImpl clone = new SPSessionImpl();

		clone.setSpSessionId(getSpSessionId());
		clone.setCompanyId(getCompanyId());
		clone.setUserId(getUserId());
		clone.setCreateDate(getCreateDate());
		clone.setSsoSessionId(getSsoSessionId());
		clone.setIssuer(getIssuer());

		return clone;
	}

	public int compareTo(SPSession spSession) {
		long pk = spSession.getPrimaryKey();

		if (getPrimaryKey() < pk) {
			return -1;
		}
		else if (getPrimaryKey() > pk) {
			return 1;
		}
		else {
			return 0;
		}
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		SPSession spSession = null;

		try {
			spSession = (SPSession)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = spSession.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{spSessionId=");
		sb.append(getSpSessionId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", ssoSessionId=");
		sb.append(getSsoSessionId());
		sb.append(", issuer=");
		sb.append(getIssuer());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.liferay.portal.saml.model.SPSession");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>spSessionId</column-name><column-value><![CDATA[");
		sb.append(getSpSessionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ssoSessionId</column-name><column-value><![CDATA[");
		sb.append(getSsoSessionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>issuer</column-name><column-value><![CDATA[");
		sb.append(getIssuer());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _spSessionId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private long _ssoSessionId;
	private long _originalSsoSessionId;
	private boolean _setOriginalSsoSessionId;
	private String _issuer;
	private String _originalIssuer;
	private transient ExpandoBridge _expandoBridge;
}