create table CalendarBooking (
	uuid_ VARCHAR(75) null,
	calendarBookingId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	calendarEventId LONG,
	calendarResourceId LONG,
	classNameId LONG,
	classPK LONG,
	title STRING null,
	name STRING null,
	description STRING null,
	location STRING null,
	startDate DATE null,
	endDate DATE null,
	durationHour INTEGER,
	durationMinute INTEGER,
	recurrence VARCHAR(75) null,
	type_ VARCHAR(75) null,
	required BOOLEAN
);

create table CalendarEvent (
	uuid_ VARCHAR(75) null,
	calendarEventId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	title STRING null,
	description STRING null,
	location STRING null,
	startDate DATE null,
	endDate DATE null,
	durationHour INTEGER,
	durationMinute INTEGER,
	allDay BOOLEAN,
	recurrence VARCHAR(75) null,
	type_ VARCHAR(75) null,
	remindBy INTEGER,
	firstReminder INTEGER,
	secondReminder INTEGER
);

create table CalendarResource (
	uuid_ VARCHAR(75) null,
	calendarResourceId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	classNameId LONG,
	classPK LONG,
	classUuid VARCHAR(75) null,
	name STRING null,
	description STRING null,
	active_ BOOLEAN
);