/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.workflow.kaleo.util;

import com.liferay.portal.DuplicateRoleException;
import com.liferay.portal.NoSuchRoleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.Role;
import com.liferay.portal.model.RoleConstants;
import com.liferay.portal.service.RoleLocalService;
import com.liferay.portal.service.RoleLocalServiceUtil;
import com.liferay.portal.service.ServiceContext;

import java.util.ArrayList;
import java.util.List;

/**
 * <a href="RoleRetrievalUtil.java.html"><b><i>View Source</i></b></a>
 *
 * @author Michael C. Han
 */
public class RoleRetrievalUtil {

	public static Role getRole(
			String roleName, int roleType, boolean autoCreate,
			RoleLocalService roleLocalService, ServiceContext serviceContext)
		throws SystemException, PortalException {

		Role role = null;

		try {
			role = roleLocalService.getRole(
				serviceContext.getCompanyId(),
				roleName);

			if (role.getType() != roleType) {
				throw new DuplicateRoleException(
					"Role already exists with name: " + roleName);
			}
		}
		catch (NoSuchRoleException nsre) {
			if (!autoCreate) {
				throw nsre;
			}

			role = roleLocalService.addRole(
				serviceContext.getUserId(),
				serviceContext.getCompanyId(),
				roleName, null,
				"Autogenerated role from workflow definition",
				roleType);
		}

		return role;
	}

	public static List<Long> getRoleIds(ServiceContext serviceContext)
		throws PortalException, SystemException {

		List<Role> roles = RoleLocalServiceUtil.getUserRoles(
			serviceContext.getUserId());

		List<Long> roleIds = new ArrayList<Long>(
			roles.size());

		for (Role role : roles) {
			roleIds.add(role.getRoleId());
		}
		
		return roleIds;
	}

	public static int getRoleType(String roleType) {
		if (roleType.equals(RoleConstants.TYPE_COMMUNITY_LABEL)) {
			return RoleConstants.TYPE_COMMUNITY;
		}
		if (roleType.equals(RoleConstants.TYPE_ORGANIZATION)) {
			return RoleConstants.TYPE_ORGANIZATION;
		}

		return RoleConstants.TYPE_REGULAR;
	}

}