/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.shortlink.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ShortLinkEntry service. Represents a row in the &quot;ShortLink_ShortLinkEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.shortlink.model.impl.ShortLinkEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.shortlink.model.impl.ShortLinkEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ShortLinkEntry
 * @see com.liferay.shortlink.model.impl.ShortLinkEntryImpl
 * @see com.liferay.shortlink.model.impl.ShortLinkEntryModelImpl
 * @generated
 */
public interface ShortLinkEntryModel extends BaseModel<ShortLinkEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a short link entry model instance should use the {@link ShortLinkEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this short link entry.
	 *
	 * @return the primary key of this short link entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this short link entry.
	 *
	 * @param primaryKey the primary key of this short link entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this short link entry.
	 *
	 * @return the uuid of this short link entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this short link entry.
	 *
	 * @param uuid the uuid of this short link entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the short link entry ID of this short link entry.
	 *
	 * @return the short link entry ID of this short link entry
	 */
	public long getShortLinkEntryId();

	/**
	 * Sets the short link entry ID of this short link entry.
	 *
	 * @param shortLinkEntryId the short link entry ID of this short link entry
	 */
	public void setShortLinkEntryId(long shortLinkEntryId);

	/**
	 * Returns the create date of this short link entry.
	 *
	 * @return the create date of this short link entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this short link entry.
	 *
	 * @param createDate the create date of this short link entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this short link entry.
	 *
	 * @return the modified date of this short link entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this short link entry.
	 *
	 * @param modifiedDate the modified date of this short link entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the original u r l of this short link entry.
	 *
	 * @return the original u r l of this short link entry
	 */
	@AutoEscape
	public String getOriginalURL();

	/**
	 * Sets the original u r l of this short link entry.
	 *
	 * @param originalURL the original u r l of this short link entry
	 */
	public void setOriginalURL(String originalURL);

	/**
	 * Returns the short u r l of this short link entry.
	 *
	 * @return the short u r l of this short link entry
	 */
	@AutoEscape
	public String getShortURL();

	/**
	 * Sets the short u r l of this short link entry.
	 *
	 * @param shortURL the short u r l of this short link entry
	 */
	public void setShortURL(String shortURL);

	/**
	 * Returns the autogenerated of this short link entry.
	 *
	 * @return the autogenerated of this short link entry
	 */
	public boolean getAutogenerated();

	/**
	 * Returns <code>true</code> if this short link entry is autogenerated.
	 *
	 * @return <code>true</code> if this short link entry is autogenerated; <code>false</code> otherwise
	 */
	public boolean isAutogenerated();

	/**
	 * Sets whether this short link entry is autogenerated.
	 *
	 * @param autogenerated the autogenerated of this short link entry
	 */
	public void setAutogenerated(boolean autogenerated);

	/**
	 * Returns the active of this short link entry.
	 *
	 * @return the active of this short link entry
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this short link entry is active.
	 *
	 * @return <code>true</code> if this short link entry is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this short link entry is active.
	 *
	 * @param active the active of this short link entry
	 */
	public void setActive(boolean active);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.shortlink.model.ShortLinkEntry shortLinkEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.shortlink.model.ShortLinkEntry> toCacheModel();

	@Override
	public com.liferay.shortlink.model.ShortLinkEntry toEscapedModel();

	@Override
	public com.liferay.shortlink.model.ShortLinkEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}