/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sharing.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.liferay.sharing.service.persistence.SharingEntryPK;

import java.io.Serializable;

/**
 * The base model interface for the SharingEntry service. Represents a row in the &quot;Sharing_SharingEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sharing.model.impl.SharingEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sharing.model.impl.SharingEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SharingEntry
 * @see com.liferay.sharing.model.impl.SharingEntryImpl
 * @see com.liferay.sharing.model.impl.SharingEntryModelImpl
 * @generated
 */
@ProviderType
public interface SharingEntryModel extends AttachedModel, BaseModel<SharingEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sharing entry model instance should use the {@link SharingEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this sharing entry.
	 *
	 * @return the primary key of this sharing entry
	 */
	public SharingEntryPK getPrimaryKey();

	/**
	 * Sets the primary key of this sharing entry.
	 *
	 * @param primaryKey the primary key of this sharing entry
	 */
	public void setPrimaryKey(SharingEntryPK primaryKey);

	/**
	 * Returns the fully qualified class name of this sharing entry.
	 *
	 * @return the fully qualified class name of this sharing entry
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this sharing entry.
	 *
	 * @return the class name ID of this sharing entry
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this sharing entry.
	 *
	 * @param classNameId the class name ID of this sharing entry
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this sharing entry.
	 *
	 * @return the class p k of this sharing entry
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this sharing entry.
	 *
	 * @param classPK the class p k of this sharing entry
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the sharing class name ID of this sharing entry.
	 *
	 * @return the sharing class name ID of this sharing entry
	 */
	public long getSharingClassNameId();

	/**
	 * Sets the sharing class name ID of this sharing entry.
	 *
	 * @param sharingClassNameId the sharing class name ID of this sharing entry
	 */
	public void setSharingClassNameId(long sharingClassNameId);

	/**
	 * Returns the sharing class p k of this sharing entry.
	 *
	 * @return the sharing class p k of this sharing entry
	 */
	public long getSharingClassPK();

	/**
	 * Sets the sharing class p k of this sharing entry.
	 *
	 * @param sharingClassPK the sharing class p k of this sharing entry
	 */
	public void setSharingClassPK(long sharingClassPK);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SharingEntry sharingEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SharingEntry> toCacheModel();

	@Override
	public SharingEntry toEscapedModel();

	@Override
	public SharingEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}