<table>
<tr>
	<td>
		$processor.processColumn("column-1")
	</td>
	<td>
		$processor.processColumn("column-2")
	</td>
	<td>
		$processor.processColumn("column-3")
	</td>
</tr>
<tr>
	<td>
		$processor.processColumn("column-4")
	</td>
	<td colspan="2">
		$processor.processColumn("column-5")
	</td>
</tr>
<tr>
	<td>
		$processor.processColumn("column-6")
	</td>
	<td>
		$processor.processColumn("column-7")
	</td>
	<td>
		$processor.processColumn("column-8")
	</td>
</tr>
</table>