/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.hr.model.impl;

import com.liferay.hr.model.HRTimeSheetDay;
import com.liferay.hr.model.HRTimeSheetDayModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the HRTimeSheetDay service. Represents a row in the &quot;HRTimeSheetDay&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.hr.model.HRTimeSheetDayModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HRTimeSheetDayImpl}.
 * </p>
 *
 * @author Wesley Gong
 * @see HRTimeSheetDayImpl
 * @see com.liferay.hr.model.HRTimeSheetDay
 * @see com.liferay.hr.model.HRTimeSheetDayModel
 * @generated
 */
public class HRTimeSheetDayModelImpl extends BaseModelImpl<HRTimeSheetDay>
	implements HRTimeSheetDayModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a h r time sheet day model instance should use the {@link com.liferay.hr.model.HRTimeSheetDay} interface instead.
	 */
	public static final String TABLE_NAME = "HRTimeSheetDay";
	public static final Object[][] TABLE_COLUMNS = {
			{ "hrTimeSheetDayId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "hrTimeSheetId", Types.BIGINT },
			{ "hrUserId", Types.BIGINT },
			{ "dayOfYear", Types.INTEGER },
			{ "year", Types.INTEGER },
			{ "hours", Types.DOUBLE }
		};
	public static final String TABLE_SQL_CREATE = "create table HRTimeSheetDay (hrTimeSheetDayId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,hrTimeSheetId LONG,hrUserId LONG,dayOfYear INTEGER,year INTEGER,hours DOUBLE)";
	public static final String TABLE_SQL_DROP = "drop table HRTimeSheetDay";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.hr.model.HRTimeSheetDay"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.hr.model.HRTimeSheetDay"),
			true);

	public Class<?> getModelClass() {
		return HRTimeSheetDay.class;
	}

	public String getModelClassName() {
		return HRTimeSheetDay.class.getName();
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.hr.model.HRTimeSheetDay"));

	public HRTimeSheetDayModelImpl() {
	}

	public long getPrimaryKey() {
		return _hrTimeSheetDayId;
	}

	public void setPrimaryKey(long primaryKey) {
		setHrTimeSheetDayId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_hrTimeSheetDayId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public long getHrTimeSheetDayId() {
		return _hrTimeSheetDayId;
	}

	public void setHrTimeSheetDayId(long hrTimeSheetDayId) {
		_hrTimeSheetDayId = hrTimeSheetDayId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	public void setUserName(String userName) {
		_userName = userName;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getHrTimeSheetId() {
		return _hrTimeSheetId;
	}

	public void setHrTimeSheetId(long hrTimeSheetId) {
		_hrTimeSheetId = hrTimeSheetId;
	}

	public long getHrUserId() {
		return _hrUserId;
	}

	public void setHrUserId(long hrUserId) {
		_hrUserId = hrUserId;
	}

	public String getHrUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getHrUserId(), "uuid", _hrUserUuid);
	}

	public void setHrUserUuid(String hrUserUuid) {
		_hrUserUuid = hrUserUuid;
	}

	public int getDayOfYear() {
		return _dayOfYear;
	}

	public void setDayOfYear(int dayOfYear) {
		_dayOfYear = dayOfYear;
	}

	public int getYear() {
		return _year;
	}

	public void setYear(int year) {
		_year = year;
	}

	public double getHours() {
		return _hours;
	}

	public void setHours(double hours) {
		_hours = hours;
	}

	@Override
	public HRTimeSheetDay toEscapedModel() {
		if (isEscapedModel()) {
			return (HRTimeSheetDay)this;
		}
		else {
			if (_escapedModelProxy == null) {
				_escapedModelProxy = (HRTimeSheetDay)Proxy.newProxyInstance(_classLoader,
						_escapedModelProxyInterfaces,
						new AutoEscapeBeanHandler(this));
			}

			return _escapedModelProxy;
		}
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
					HRTimeSheetDay.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		HRTimeSheetDayImpl hrTimeSheetDayImpl = new HRTimeSheetDayImpl();

		hrTimeSheetDayImpl.setHrTimeSheetDayId(getHrTimeSheetDayId());
		hrTimeSheetDayImpl.setGroupId(getGroupId());
		hrTimeSheetDayImpl.setCompanyId(getCompanyId());
		hrTimeSheetDayImpl.setUserId(getUserId());
		hrTimeSheetDayImpl.setUserName(getUserName());
		hrTimeSheetDayImpl.setCreateDate(getCreateDate());
		hrTimeSheetDayImpl.setModifiedDate(getModifiedDate());
		hrTimeSheetDayImpl.setHrTimeSheetId(getHrTimeSheetId());
		hrTimeSheetDayImpl.setHrUserId(getHrUserId());
		hrTimeSheetDayImpl.setDayOfYear(getDayOfYear());
		hrTimeSheetDayImpl.setYear(getYear());
		hrTimeSheetDayImpl.setHours(getHours());

		hrTimeSheetDayImpl.resetOriginalValues();

		return hrTimeSheetDayImpl;
	}

	public int compareTo(HRTimeSheetDay hrTimeSheetDay) {
		long primaryKey = hrTimeSheetDay.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		HRTimeSheetDay hrTimeSheetDay = null;

		try {
			hrTimeSheetDay = (HRTimeSheetDay)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = hrTimeSheetDay.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<HRTimeSheetDay> toCacheModel() {
		HRTimeSheetDayCacheModel hrTimeSheetDayCacheModel = new HRTimeSheetDayCacheModel();

		hrTimeSheetDayCacheModel.hrTimeSheetDayId = getHrTimeSheetDayId();

		hrTimeSheetDayCacheModel.groupId = getGroupId();

		hrTimeSheetDayCacheModel.companyId = getCompanyId();

		hrTimeSheetDayCacheModel.userId = getUserId();

		hrTimeSheetDayCacheModel.userName = getUserName();

		String userName = hrTimeSheetDayCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			hrTimeSheetDayCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			hrTimeSheetDayCacheModel.createDate = createDate.getTime();
		}
		else {
			hrTimeSheetDayCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			hrTimeSheetDayCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			hrTimeSheetDayCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		hrTimeSheetDayCacheModel.hrTimeSheetId = getHrTimeSheetId();

		hrTimeSheetDayCacheModel.hrUserId = getHrUserId();

		hrTimeSheetDayCacheModel.dayOfYear = getDayOfYear();

		hrTimeSheetDayCacheModel.year = getYear();

		hrTimeSheetDayCacheModel.hours = getHours();

		return hrTimeSheetDayCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{hrTimeSheetDayId=");
		sb.append(getHrTimeSheetDayId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", hrTimeSheetId=");
		sb.append(getHrTimeSheetId());
		sb.append(", hrUserId=");
		sb.append(getHrUserId());
		sb.append(", dayOfYear=");
		sb.append(getDayOfYear());
		sb.append(", year=");
		sb.append(getYear());
		sb.append(", hours=");
		sb.append(getHours());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.liferay.hr.model.HRTimeSheetDay");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>hrTimeSheetDayId</column-name><column-value><![CDATA[");
		sb.append(getHrTimeSheetDayId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hrTimeSheetId</column-name><column-value><![CDATA[");
		sb.append(getHrTimeSheetId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hrUserId</column-name><column-value><![CDATA[");
		sb.append(getHrUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dayOfYear</column-name><column-value><![CDATA[");
		sb.append(getDayOfYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>year</column-name><column-value><![CDATA[");
		sb.append(getYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hours</column-name><column-value><![CDATA[");
		sb.append(getHours());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = HRTimeSheetDay.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			HRTimeSheetDay.class
		};
	private long _hrTimeSheetDayId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _hrTimeSheetId;
	private long _hrUserId;
	private String _hrUserUuid;
	private int _dayOfYear;
	private int _year;
	private double _hours;
	private transient ExpandoBridge _expandoBridge;
	private HRTimeSheetDay _escapedModelProxy;
}