<?xml version="1.0"?>

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:v2bind="urn:oasis:names:tc:wsrp:v2:bind" xmlns:v1bind="urn:oasis:names:tc:wsrp:v1:bind" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="urn:oasis:names:tc:wsrp:v2:wsdl">
	<import namespace="urn:oasis:names:tc:wsrp:v1:bind" location="wsrp-1.0-bindings.wsdl"/>
	<import namespace="urn:oasis:names:tc:wsrp:v2:bind" location="wsrp-2.0-bindings.wsdl"/>
	<wsdl:service name="WSRP_v1_Service">
		<wsdl:port binding="v1bind:WSRP_v1_Markup_Binding_SOAP" name="WSRP_v1_Markup_Service">
			<soap:address location="http://my.service:8080/services/WSRPBaseService?wsrpProducerUuid=${wsrpProducerUuid}"/>
		</wsdl:port>
		<wsdl:port binding="v1bind:WSRP_v1_ServiceDescription_Binding_SOAP" name="WSRP_v1_ServiceDescription_Service">
			<soap:address location="http://my.service:8080/services/WSRPServiceDescriptionService?wsrpProducerUuid=${wsrpProducerUuid}"/>
		</wsdl:port>
		<wsdl:port binding="v1bind:WSRP_v1_Registration_Binding_SOAP" name="WSRP_v1_Registration_Service">
			<soap:address location="http://my.service:8080/services/WSRPRegistrationService?wsrpProducerUuid=${wsrpProducerUuid}"/>
		</wsdl:port>
		<wsdl:port binding="v1bind:WSRP_v1_PortletManagement_Binding_SOAP" name="WSRP_v1_PortletManagement_Service">
			<soap:address location="http://my.service:8080/services/WSRPPortletManagementService?wsrpProducerUuid=${wsrpProducerUuid}"/>
		</wsdl:port>
	</wsdl:service>
	<wsdl:service name="WSRP_v2_Service">
		<wsdl:port binding="v2bind:WSRP_v2_Markup_Binding_SOAP" name="WSRP_v2_Markup_Service">
			<soap:address location="http://my.service:8080/services/WSRP_v2_Markup_Service?wsrpProducerUuid=${wsrpProducerUuid}"/>
		</wsdl:port>
		<wsdl:port binding="v2bind:WSRP_v2_ServiceDescription_Binding_SOAP" name="WSRP_v2_ServiceDescription_Service">
			<soap:address location="http://my.service:8080/services/WSRP_v2_ServiceDescription_Service?wsrpProducerUuid=${wsrpProducerUuid}"/>
		</wsdl:port>
		<wsdl:port binding="v2bind:WSRP_v2_Registration_Binding_SOAP" name="WSRP_v2_Registration_Service">
			<soap:address location="http://my.service:8080/services/WSRP_v2_Registration_Service?wsrpProducerUuid=${wsrpProducerUuid}"/>
		</wsdl:port>
		<wsdl:port binding="v2bind:WSRP_v2_PortletManagement_Binding_SOAP" name="WSRP_v2_PortletManagement_Service">
			<soap:address location="http://my.service:8080/services/WSRP_v2_PortletManagement_Service?wsrpProducerUuid=${wsrpProducerUuid}"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>