/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.bbb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BBBParticipant service. Represents a row in the &quot;BBBParticipant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.bbb.model.impl.BBBParticipantModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.bbb.model.impl.BBBParticipantImpl}.
 * </p>
 *
 * @author Shinn Lok
 * @see BBBParticipant
 * @see com.liferay.bbb.model.impl.BBBParticipantImpl
 * @see com.liferay.bbb.model.impl.BBBParticipantModelImpl
 * @generated
 */
public interface BBBParticipantModel extends BaseModel<BBBParticipant>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a b b b participant model instance should use the {@link BBBParticipant} interface instead.
	 */

	/**
	 * Returns the primary key of this b b b participant.
	 *
	 * @return the primary key of this b b b participant
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this b b b participant.
	 *
	 * @param primaryKey the primary key of this b b b participant
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bbb participant ID of this b b b participant.
	 *
	 * @return the bbb participant ID of this b b b participant
	 */
	public long getBbbParticipantId();

	/**
	 * Sets the bbb participant ID of this b b b participant.
	 *
	 * @param bbbParticipantId the bbb participant ID of this b b b participant
	 */
	public void setBbbParticipantId(long bbbParticipantId);

	/**
	 * Returns the group ID of this b b b participant.
	 *
	 * @return the group ID of this b b b participant
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this b b b participant.
	 *
	 * @param groupId the group ID of this b b b participant
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this b b b participant.
	 *
	 * @return the company ID of this b b b participant
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this b b b participant.
	 *
	 * @param companyId the company ID of this b b b participant
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this b b b participant.
	 *
	 * @return the user ID of this b b b participant
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this b b b participant.
	 *
	 * @param userId the user ID of this b b b participant
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this b b b participant.
	 *
	 * @return the user uuid of this b b b participant
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this b b b participant.
	 *
	 * @param userUuid the user uuid of this b b b participant
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this b b b participant.
	 *
	 * @return the user name of this b b b participant
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this b b b participant.
	 *
	 * @param userName the user name of this b b b participant
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this b b b participant.
	 *
	 * @return the create date of this b b b participant
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this b b b participant.
	 *
	 * @param createDate the create date of this b b b participant
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this b b b participant.
	 *
	 * @return the modified date of this b b b participant
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this b b b participant.
	 *
	 * @param modifiedDate the modified date of this b b b participant
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the bbb meeting ID of this b b b participant.
	 *
	 * @return the bbb meeting ID of this b b b participant
	 */
	public long getBbbMeetingId();

	/**
	 * Sets the bbb meeting ID of this b b b participant.
	 *
	 * @param bbbMeetingId the bbb meeting ID of this b b b participant
	 */
	public void setBbbMeetingId(long bbbMeetingId);

	/**
	 * Returns the name of this b b b participant.
	 *
	 * @return the name of this b b b participant
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this b b b participant.
	 *
	 * @param name the name of this b b b participant
	 */
	public void setName(String name);

	/**
	 * Returns the email address of this b b b participant.
	 *
	 * @return the email address of this b b b participant
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this b b b participant.
	 *
	 * @param emailAddress the email address of this b b b participant
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the type of this b b b participant.
	 *
	 * @return the type of this b b b participant
	 */
	public int getType();

	/**
	 * Sets the type of this b b b participant.
	 *
	 * @param type the type of this b b b participant
	 */
	public void setType(int type);

	/**
	 * Returns the status of this b b b participant.
	 *
	 * @return the status of this b b b participant
	 */
	public int getStatus();

	/**
	 * Sets the status of this b b b participant.
	 *
	 * @param status the status of this b b b participant
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BBBParticipant bbbParticipant);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BBBParticipant> toCacheModel();

	@Override
	public BBBParticipant toEscapedModel();

	@Override
	public BBBParticipant toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}