/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.hr.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the HRAssetDefinition service. Represents a row in the &quot;HRAssetDefinition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.hr.model.impl.HRAssetDefinitionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.hr.model.impl.HRAssetDefinitionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HRAssetDefinition
 * @see com.liferay.hr.model.impl.HRAssetDefinitionImpl
 * @see com.liferay.hr.model.impl.HRAssetDefinitionModelImpl
 * @generated
 */
public interface HRAssetDefinitionModel extends BaseModel<HRAssetDefinition>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a h r asset definition model instance should use the {@link HRAssetDefinition} interface instead.
	 */

	/**
	 * Gets the primary key of this h r asset definition.
	 *
	 * @return the primary key of this h r asset definition
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this h r asset definition
	 *
	 * @param pk the primary key of this h r asset definition
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the hr asset definition ID of this h r asset definition.
	 *
	 * @return the hr asset definition ID of this h r asset definition
	 */
	public long getHrAssetDefinitionId();

	/**
	 * Sets the hr asset definition ID of this h r asset definition.
	 *
	 * @param hrAssetDefinitionId the hr asset definition ID of this h r asset definition
	 */
	public void setHrAssetDefinitionId(long hrAssetDefinitionId);

	/**
	 * Gets the group ID of this h r asset definition.
	 *
	 * @return the group ID of this h r asset definition
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this h r asset definition.
	 *
	 * @param groupId the group ID of this h r asset definition
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company ID of this h r asset definition.
	 *
	 * @return the company ID of this h r asset definition
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this h r asset definition.
	 *
	 * @param companyId the company ID of this h r asset definition
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user ID of this h r asset definition.
	 *
	 * @return the user ID of this h r asset definition
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this h r asset definition.
	 *
	 * @param userId the user ID of this h r asset definition
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this h r asset definition.
	 *
	 * @return the user uuid of this h r asset definition
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this h r asset definition.
	 *
	 * @param userUuid the user uuid of this h r asset definition
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the user name of this h r asset definition.
	 *
	 * @return the user name of this h r asset definition
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this h r asset definition.
	 *
	 * @param userName the user name of this h r asset definition
	 */
	public void setUserName(String userName);

	/**
	 * Gets the create date of this h r asset definition.
	 *
	 * @return the create date of this h r asset definition
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this h r asset definition.
	 *
	 * @param createDate the create date of this h r asset definition
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Gets the modified date of this h r asset definition.
	 *
	 * @return the modified date of this h r asset definition
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this h r asset definition.
	 *
	 * @param modifiedDate the modified date of this h r asset definition
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the hr asset product ID of this h r asset definition.
	 *
	 * @return the hr asset product ID of this h r asset definition
	 */
	@AutoEscape
	public String getHrAssetProductId();

	/**
	 * Sets the hr asset product ID of this h r asset definition.
	 *
	 * @param hrAssetProductId the hr asset product ID of this h r asset definition
	 */
	public void setHrAssetProductId(String hrAssetProductId);

	/**
	 * Gets the hr asset type ID of this h r asset definition.
	 *
	 * @return the hr asset type ID of this h r asset definition
	 */
	public long getHrAssetTypeId();

	/**
	 * Sets the hr asset type ID of this h r asset definition.
	 *
	 * @param hrAssetTypeId the hr asset type ID of this h r asset definition
	 */
	public void setHrAssetTypeId(long hrAssetTypeId);

	/**
	 * Gets the hr asset vendor ID of this h r asset definition.
	 *
	 * @return the hr asset vendor ID of this h r asset definition
	 */
	public long getHrAssetVendorId();

	/**
	 * Sets the hr asset vendor ID of this h r asset definition.
	 *
	 * @param hrAssetVendorId the hr asset vendor ID of this h r asset definition
	 */
	public void setHrAssetVendorId(long hrAssetVendorId);

	/**
	 * Gets the definition number of this h r asset definition.
	 *
	 * @return the definition number of this h r asset definition
	 */
	@AutoEscape
	public String getDefinitionNumber();

	/**
	 * Sets the definition number of this h r asset definition.
	 *
	 * @param definitionNumber the definition number of this h r asset definition
	 */
	public void setDefinitionNumber(String definitionNumber);

	/**
	 * Gets the order ID of this h r asset definition.
	 *
	 * @return the order ID of this h r asset definition
	 */
	public Date getOrderId();

	/**
	 * Sets the order ID of this h r asset definition.
	 *
	 * @param orderId the order ID of this h r asset definition
	 */
	public void setOrderId(Date orderId);

	/**
	 * Gets the order date of this h r asset definition.
	 *
	 * @return the order date of this h r asset definition
	 */
	public Date getOrderDate();

	/**
	 * Sets the order date of this h r asset definition.
	 *
	 * @param orderDate the order date of this h r asset definition
	 */
	public void setOrderDate(Date orderDate);

	/**
	 * Gets the quantity of this h r asset definition.
	 *
	 * @return the quantity of this h r asset definition
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this h r asset definition.
	 *
	 * @param quantity the quantity of this h r asset definition
	 */
	public void setQuantity(int quantity);

	/**
	 * Gets the individual price of this h r asset definition.
	 *
	 * @return the individual price of this h r asset definition
	 */
	public double getIndividualPrice();

	/**
	 * Sets the individual price of this h r asset definition.
	 *
	 * @param individualPrice the individual price of this h r asset definition
	 */
	public void setIndividualPrice(double individualPrice);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(HRAssetDefinition hrAssetDefinition);

	public int hashCode();

	public HRAssetDefinition toEscapedModel();

	public String toString();

	public String toXmlString();
}