/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.hr.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the HRExpense service. Represents a row in the &quot;HRExpense&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.hr.model.impl.HRExpenseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.hr.model.impl.HRExpenseImpl}.
 * </p>
 *
 * @author Wesley Gong
 * @see HRExpense
 * @see com.liferay.hr.model.impl.HRExpenseImpl
 * @see com.liferay.hr.model.impl.HRExpenseModelImpl
 * @generated
 */
public interface HRExpenseModel extends BaseModel<HRExpense>, GroupedModel,
	WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a h r expense model instance should use the {@link HRExpense} interface instead.
	 */

	/**
	 * Returns the primary key of this h r expense.
	 *
	 * @return the primary key of this h r expense
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this h r expense.
	 *
	 * @param primaryKey the primary key of this h r expense
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the hr expense ID of this h r expense.
	 *
	 * @return the hr expense ID of this h r expense
	 */
	public long getHrExpenseId();

	/**
	 * Sets the hr expense ID of this h r expense.
	 *
	 * @param hrExpenseId the hr expense ID of this h r expense
	 */
	public void setHrExpenseId(long hrExpenseId);

	/**
	 * Returns the group ID of this h r expense.
	 *
	 * @return the group ID of this h r expense
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this h r expense.
	 *
	 * @param groupId the group ID of this h r expense
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this h r expense.
	 *
	 * @return the company ID of this h r expense
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this h r expense.
	 *
	 * @param companyId the company ID of this h r expense
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this h r expense.
	 *
	 * @return the user ID of this h r expense
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this h r expense.
	 *
	 * @param userId the user ID of this h r expense
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this h r expense.
	 *
	 * @return the user uuid of this h r expense
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this h r expense.
	 *
	 * @param userUuid the user uuid of this h r expense
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this h r expense.
	 *
	 * @return the user name of this h r expense
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this h r expense.
	 *
	 * @param userName the user name of this h r expense
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this h r expense.
	 *
	 * @return the create date of this h r expense
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this h r expense.
	 *
	 * @param createDate the create date of this h r expense
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this h r expense.
	 *
	 * @return the modified date of this h r expense
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this h r expense.
	 *
	 * @param modifiedDate the modified date of this h r expense
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the hr expense account ID of this h r expense.
	 *
	 * @return the hr expense account ID of this h r expense
	 */
	public long getHrExpenseAccountId();

	/**
	 * Sets the hr expense account ID of this h r expense.
	 *
	 * @param hrExpenseAccountId the hr expense account ID of this h r expense
	 */
	public void setHrExpenseAccountId(long hrExpenseAccountId);

	/**
	 * Returns the hr expense type ID of this h r expense.
	 *
	 * @return the hr expense type ID of this h r expense
	 */
	public long getHrExpenseTypeId();

	/**
	 * Sets the hr expense type ID of this h r expense.
	 *
	 * @param hrExpenseTypeId the hr expense type ID of this h r expense
	 */
	public void setHrExpenseTypeId(long hrExpenseTypeId);

	/**
	 * Returns the hr user ID of this h r expense.
	 *
	 * @return the hr user ID of this h r expense
	 */
	public long getHrUserId();

	/**
	 * Sets the hr user ID of this h r expense.
	 *
	 * @param hrUserId the hr user ID of this h r expense
	 */
	public void setHrUserId(long hrUserId);

	/**
	 * Returns the hr user uuid of this h r expense.
	 *
	 * @return the hr user uuid of this h r expense
	 * @throws SystemException if a system exception occurred
	 */
	public String getHrUserUuid() throws SystemException;

	/**
	 * Sets the hr user uuid of this h r expense.
	 *
	 * @param hrUserUuid the hr user uuid of this h r expense
	 */
	public void setHrUserUuid(String hrUserUuid);

	/**
	 * Returns the expense date of this h r expense.
	 *
	 * @return the expense date of this h r expense
	 */
	public Date getExpenseDate();

	/**
	 * Sets the expense date of this h r expense.
	 *
	 * @param expenseDate the expense date of this h r expense
	 */
	public void setExpenseDate(Date expenseDate);

	/**
	 * Returns the expense amount of this h r expense.
	 *
	 * @return the expense amount of this h r expense
	 */
	public double getExpenseAmount();

	/**
	 * Sets the expense amount of this h r expense.
	 *
	 * @param expenseAmount the expense amount of this h r expense
	 */
	public void setExpenseAmount(double expenseAmount);

	/**
	 * Returns the expense h r expense currency ID of this h r expense.
	 *
	 * @return the expense h r expense currency ID of this h r expense
	 */
	public long getExpenseHRExpenseCurrencyId();

	/**
	 * Sets the expense h r expense currency ID of this h r expense.
	 *
	 * @param expenseHRExpenseCurrencyId the expense h r expense currency ID of this h r expense
	 */
	public void setExpenseHRExpenseCurrencyId(long expenseHRExpenseCurrencyId);

	/**
	 * Returns the reimbursement amount of this h r expense.
	 *
	 * @return the reimbursement amount of this h r expense
	 */
	public double getReimbursementAmount();

	/**
	 * Sets the reimbursement amount of this h r expense.
	 *
	 * @param reimbursementAmount the reimbursement amount of this h r expense
	 */
	public void setReimbursementAmount(double reimbursementAmount);

	/**
	 * Returns the reimbursement h r expense currency ID of this h r expense.
	 *
	 * @return the reimbursement h r expense currency ID of this h r expense
	 */
	public long getReimbursementHRExpenseCurrencyId();

	/**
	 * Sets the reimbursement h r expense currency ID of this h r expense.
	 *
	 * @param reimbursementHRExpenseCurrencyId the reimbursement h r expense currency ID of this h r expense
	 */
	public void setReimbursementHRExpenseCurrencyId(
		long reimbursementHRExpenseCurrencyId);

	/**
	 * Returns the status of this h r expense.
	 *
	 * @return the status of this h r expense
	 */
	public int getStatus();

	/**
	 * Sets the status of this h r expense.
	 *
	 * @param status the status of this h r expense
	 */
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this h r expense.
	 *
	 * @return the status by user ID of this h r expense
	 */
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this h r expense.
	 *
	 * @param statusByUserId the status by user ID of this h r expense
	 */
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this h r expense.
	 *
	 * @return the status by user uuid of this h r expense
	 * @throws SystemException if a system exception occurred
	 */
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this h r expense.
	 *
	 * @param statusByUserUuid the status by user uuid of this h r expense
	 */
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this h r expense.
	 *
	 * @return the status by user name of this h r expense
	 */
	@AutoEscape
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this h r expense.
	 *
	 * @param statusByUserName the status by user name of this h r expense
	 */
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this h r expense.
	 *
	 * @return the status date of this h r expense
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this h r expense.
	 *
	 * @param statusDate the status date of this h r expense
	 */
	public void setStatusDate(Date statusDate);

	/**
	 * @deprecated Renamed to {@link #isApproved()}
	 */
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this h r expense is approved.
	 *
	 * @return <code>true</code> if this h r expense is approved; <code>false</code> otherwise
	 */
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this h r expense is a draft.
	 *
	 * @return <code>true</code> if this h r expense is a draft; <code>false</code> otherwise
	 */
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this h r expense is expired.
	 *
	 * @return <code>true</code> if this h r expense is expired; <code>false</code> otherwise
	 */
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this h r expense is pending.
	 *
	 * @return <code>true</code> if this h r expense is pending; <code>false</code> otherwise
	 */
	public boolean isPending();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(HRExpense hrExpense);

	public int hashCode();

	public HRExpense toEscapedModel();

	public String toString();

	public String toXmlString();
}