/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.hr.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the HRHoliday service. Represents a row in the &quot;HRHoliday&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.hr.model.impl.HRHolidayModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.hr.model.impl.HRHolidayImpl}.
 * </p>
 *
 * @author Wesley Gong
 * @see HRHoliday
 * @see com.liferay.hr.model.impl.HRHolidayImpl
 * @see com.liferay.hr.model.impl.HRHolidayModelImpl
 * @generated
 */
public interface HRHolidayModel extends BaseModel<HRHoliday>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a h r holiday model instance should use the {@link HRHoliday} interface instead.
	 */

	/**
	 * Returns the primary key of this h r holiday.
	 *
	 * @return the primary key of this h r holiday
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this h r holiday.
	 *
	 * @param primaryKey the primary key of this h r holiday
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the hr holiday ID of this h r holiday.
	 *
	 * @return the hr holiday ID of this h r holiday
	 */
	public long getHrHolidayId();

	/**
	 * Sets the hr holiday ID of this h r holiday.
	 *
	 * @param hrHolidayId the hr holiday ID of this h r holiday
	 */
	public void setHrHolidayId(long hrHolidayId);

	/**
	 * Returns the group ID of this h r holiday.
	 *
	 * @return the group ID of this h r holiday
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this h r holiday.
	 *
	 * @param groupId the group ID of this h r holiday
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this h r holiday.
	 *
	 * @return the company ID of this h r holiday
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this h r holiday.
	 *
	 * @param companyId the company ID of this h r holiday
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this h r holiday.
	 *
	 * @return the user ID of this h r holiday
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this h r holiday.
	 *
	 * @param userId the user ID of this h r holiday
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this h r holiday.
	 *
	 * @return the user uuid of this h r holiday
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this h r holiday.
	 *
	 * @param userUuid the user uuid of this h r holiday
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this h r holiday.
	 *
	 * @return the user name of this h r holiday
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this h r holiday.
	 *
	 * @param userName the user name of this h r holiday
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this h r holiday.
	 *
	 * @return the create date of this h r holiday
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this h r holiday.
	 *
	 * @param createDate the create date of this h r holiday
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this h r holiday.
	 *
	 * @return the modified date of this h r holiday
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this h r holiday.
	 *
	 * @param modifiedDate the modified date of this h r holiday
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this h r holiday.
	 *
	 * @return the name of this h r holiday
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this h r holiday.
	 *
	 * @param name the name of this h r holiday
	 */
	public void setName(String name);

	/**
	 * Returns the description of this h r holiday.
	 *
	 * @return the description of this h r holiday
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this h r holiday.
	 *
	 * @param description the description of this h r holiday
	 */
	public void setDescription(String description);

	/**
	 * Returns the day of year of this h r holiday.
	 *
	 * @return the day of year of this h r holiday
	 */
	public int getDayOfYear();

	/**
	 * Sets the day of year of this h r holiday.
	 *
	 * @param dayOfYear the day of year of this h r holiday
	 */
	public void setDayOfYear(int dayOfYear);

	/**
	 * Returns the year of this h r holiday.
	 *
	 * @return the year of this h r holiday
	 */
	public int getYear();

	/**
	 * Sets the year of this h r holiday.
	 *
	 * @param year the year of this h r holiday
	 */
	public void setYear(int year);

	/**
	 * Returns the paid of this h r holiday.
	 *
	 * @return the paid of this h r holiday
	 */
	public boolean getPaid();

	/**
	 * Returns <code>true</code> if this h r holiday is paid.
	 *
	 * @return <code>true</code> if this h r holiday is paid; <code>false</code> otherwise
	 */
	public boolean isPaid();

	/**
	 * Sets whether this h r holiday is paid.
	 *
	 * @param paid the paid of this h r holiday
	 */
	public void setPaid(boolean paid);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(HRHoliday hrHoliday);

	public int hashCode();

	public HRHoliday toEscapedModel();

	public String toString();

	public String toXmlString();
}