/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.hr.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the HRTimeOffFrequencyType service. Represents a row in the &quot;HRTimeOffFrequencyType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.hr.model.impl.HRTimeOffFrequencyTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.hr.model.impl.HRTimeOffFrequencyTypeImpl}.
 * </p>
 *
 * @author Wesley Gong
 * @see HRTimeOffFrequencyType
 * @see com.liferay.hr.model.impl.HRTimeOffFrequencyTypeImpl
 * @see com.liferay.hr.model.impl.HRTimeOffFrequencyTypeModelImpl
 * @generated
 */
public interface HRTimeOffFrequencyTypeModel extends BaseModel<HRTimeOffFrequencyType>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a h r time off frequency type model instance should use the {@link HRTimeOffFrequencyType} interface instead.
	 */

	/**
	 * Returns the primary key of this h r time off frequency type.
	 *
	 * @return the primary key of this h r time off frequency type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this h r time off frequency type.
	 *
	 * @param primaryKey the primary key of this h r time off frequency type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the hr time off frequency type ID of this h r time off frequency type.
	 *
	 * @return the hr time off frequency type ID of this h r time off frequency type
	 */
	public long getHrTimeOffFrequencyTypeId();

	/**
	 * Sets the hr time off frequency type ID of this h r time off frequency type.
	 *
	 * @param hrTimeOffFrequencyTypeId the hr time off frequency type ID of this h r time off frequency type
	 */
	public void setHrTimeOffFrequencyTypeId(long hrTimeOffFrequencyTypeId);

	/**
	 * Returns the group ID of this h r time off frequency type.
	 *
	 * @return the group ID of this h r time off frequency type
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this h r time off frequency type.
	 *
	 * @param groupId the group ID of this h r time off frequency type
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this h r time off frequency type.
	 *
	 * @return the company ID of this h r time off frequency type
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this h r time off frequency type.
	 *
	 * @param companyId the company ID of this h r time off frequency type
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this h r time off frequency type.
	 *
	 * @return the user ID of this h r time off frequency type
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this h r time off frequency type.
	 *
	 * @param userId the user ID of this h r time off frequency type
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this h r time off frequency type.
	 *
	 * @return the user uuid of this h r time off frequency type
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this h r time off frequency type.
	 *
	 * @param userUuid the user uuid of this h r time off frequency type
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this h r time off frequency type.
	 *
	 * @return the user name of this h r time off frequency type
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this h r time off frequency type.
	 *
	 * @param userName the user name of this h r time off frequency type
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this h r time off frequency type.
	 *
	 * @return the create date of this h r time off frequency type
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this h r time off frequency type.
	 *
	 * @param createDate the create date of this h r time off frequency type
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this h r time off frequency type.
	 *
	 * @return the modified date of this h r time off frequency type
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this h r time off frequency type.
	 *
	 * @param modifiedDate the modified date of this h r time off frequency type
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the code of this h r time off frequency type.
	 *
	 * @return the code of this h r time off frequency type
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this h r time off frequency type.
	 *
	 * @param code the code of this h r time off frequency type
	 */
	public void setCode(String code);

	/**
	 * Returns the name of this h r time off frequency type.
	 *
	 * @return the name of this h r time off frequency type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this h r time off frequency type.
	 *
	 * @param name the name of this h r time off frequency type
	 */
	public void setName(String name);

	/**
	 * Returns the description of this h r time off frequency type.
	 *
	 * @return the description of this h r time off frequency type
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this h r time off frequency type.
	 *
	 * @param description the description of this h r time off frequency type
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(HRTimeOffFrequencyType hrTimeOffFrequencyType);

	public int hashCode();

	public CacheModel<HRTimeOffFrequencyType> toCacheModel();

	public HRTimeOffFrequencyType toEscapedModel();

	public String toString();

	public String toXmlString();
}