/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.hr.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the HRUserTask service. Represents a row in the &quot;HRUserTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.hr.model.impl.HRUserTaskModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.hr.model.impl.HRUserTaskImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HRUserTask
 * @see com.liferay.hr.model.impl.HRUserTaskImpl
 * @see com.liferay.hr.model.impl.HRUserTaskModelImpl
 * @generated
 */
public interface HRUserTaskModel extends BaseModel<HRUserTask>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a h r user task model instance should use the {@link HRUserTask} interface instead.
	 */

	/**
	 * Gets the primary key of this h r user task.
	 *
	 * @return the primary key of this h r user task
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this h r user task
	 *
	 * @param pk the primary key of this h r user task
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the hr user task ID of this h r user task.
	 *
	 * @return the hr user task ID of this h r user task
	 */
	public long getHrUserTaskId();

	/**
	 * Sets the hr user task ID of this h r user task.
	 *
	 * @param hrUserTaskId the hr user task ID of this h r user task
	 */
	public void setHrUserTaskId(long hrUserTaskId);

	/**
	 * Gets the group ID of this h r user task.
	 *
	 * @return the group ID of this h r user task
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this h r user task.
	 *
	 * @param groupId the group ID of this h r user task
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company ID of this h r user task.
	 *
	 * @return the company ID of this h r user task
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this h r user task.
	 *
	 * @param companyId the company ID of this h r user task
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user ID of this h r user task.
	 *
	 * @return the user ID of this h r user task
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this h r user task.
	 *
	 * @param userId the user ID of this h r user task
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this h r user task.
	 *
	 * @return the user uuid of this h r user task
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this h r user task.
	 *
	 * @param userUuid the user uuid of this h r user task
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the user name of this h r user task.
	 *
	 * @return the user name of this h r user task
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this h r user task.
	 *
	 * @param userName the user name of this h r user task
	 */
	public void setUserName(String userName);

	/**
	 * Gets the create date of this h r user task.
	 *
	 * @return the create date of this h r user task
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this h r user task.
	 *
	 * @param createDate the create date of this h r user task
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Gets the modified date of this h r user task.
	 *
	 * @return the modified date of this h r user task
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this h r user task.
	 *
	 * @param modifiedDate the modified date of this h r user task
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the hr billability ID of this h r user task.
	 *
	 * @return the hr billability ID of this h r user task
	 */
	public long getHrBillabilityId();

	/**
	 * Sets the hr billability ID of this h r user task.
	 *
	 * @param hrBillabilityId the hr billability ID of this h r user task
	 */
	public void setHrBillabilityId(long hrBillabilityId);

	/**
	 * Gets the hr task ID of this h r user task.
	 *
	 * @return the hr task ID of this h r user task
	 */
	public long getHrTaskId();

	/**
	 * Sets the hr task ID of this h r user task.
	 *
	 * @param hrTaskId the hr task ID of this h r user task
	 */
	public void setHrTaskId(long hrTaskId);

	/**
	 * Gets the hr timesheet ID of this h r user task.
	 *
	 * @return the hr timesheet ID of this h r user task
	 */
	public long getHrTimesheetId();

	/**
	 * Sets the hr timesheet ID of this h r user task.
	 *
	 * @param hrTimesheetId the hr timesheet ID of this h r user task
	 */
	public void setHrTimesheetId(long hrTimesheetId);

	/**
	 * Gets the hr user ID of this h r user task.
	 *
	 * @return the hr user ID of this h r user task
	 */
	public long getHrUserId();

	/**
	 * Sets the hr user ID of this h r user task.
	 *
	 * @param hrUserId the hr user ID of this h r user task
	 */
	public void setHrUserId(long hrUserId);

	/**
	 * Gets the hr user uuid of this h r user task.
	 *
	 * @return the hr user uuid of this h r user task
	 * @throws SystemException if a system exception occurred
	 */
	public String getHrUserUuid() throws SystemException;

	/**
	 * Sets the hr user uuid of this h r user task.
	 *
	 * @param hrUserUuid the hr user uuid of this h r user task
	 */
	public void setHrUserUuid(String hrUserUuid);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(HRUserTask hrUserTask);

	public int hashCode();

	public HRUserTask toEscapedModel();

	public String toString();

	public String toXmlString();
}